# Generated by Django 3.2.23 on 2024-01-21 20:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainLinkTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background', models.ImageField(upload_to='background/', validators=[django.core.validators.MaxValueValidator(limit_value=10485760)])),
                ('profile_block', models.CharField(max_length=20, verbose_name='لون ملف التعريف')),
                ('url_block', models.CharField(max_length=20, validators=[django.core.validators.MaxLengthValidator(limit_value=20)], verbose_name='لون روابط')),
                ('link_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.mainlink')),
            ],
        ),
        migrations.AddField(
            model_name='mainlink',
            name='background',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.mainlinktemplate', verbose_name='بک\u200cگراند'),
        ),
    ]
