# Generated by Django 3.2.23 on 2024-01-21 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20240122_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainlinktemplate',
            name='profile_block',
            field=models.CharField(default='#eaf9f3', help_text='Make sure to put a "# before color code', max_length=20, verbose_name='لون ملف التعريف'),
        ),
        migrations.AlterField(
            model_name='mainlinktemplate',
            name='url_block',
            field=models.CharField(default='#6dafa7', help_text='Make sure to put a "# before color code', max_length=20, verbose_name='لون روابط'),
        ),
    ]
