# Generated by Django 3.2.23 on 2024-01-26 15:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_mainlinktemplate_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainlinktemplate',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mainlinktemplate',
            name='template_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=150, verbose_name='اسم القالب'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mainlinktemplate',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AlterField(
            model_name='mainlink',
            name='background',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.mainlinktemplate', verbose_name='خلفیه'),
        ),
        migrations.AlterField(
            model_name='mainlinktemplate',
            name='background',
            field=models.ImageField(upload_to='background/', verbose_name='خلفیه'),
        ),
    ]
