# Generated by Django 3.2.23 on 2024-01-26 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20240126_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainlinktemplate',
            name='template_name',
            field=models.CharField(default='them', max_length=150, verbose_name='اسم القالب'),
        ),
    ]
