# Generated by Django 3.2.23 on 2024-01-26 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_mainlinktemplate_template_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainlinktemplate',
            name='link_id',
        ),
    ]
