# Generated by Django 3.2.23 on 2024-01-29 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_remove_mainlinktemplate_link_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainlink',
            name='background',
        ),
        migrations.AddField(
            model_name='mainlink',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.mainlinktemplate', verbose_name='لون القالب'),
        ),
    ]
