# Generated by Django 3.2.23 on 2024-02-02 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20240129_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainlink',
            name='template',
            field=models.ForeignKey(blank=True, default='theme', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.mainlinktemplate', verbose_name='لون القالب'),
        ),
        migrations.AlterField(
            model_name='mainlinktemplate',
            name='template_name',
            field=models.CharField(default='theme', max_length=150, verbose_name='اسم القالب'),
        ),
    ]
