# Generated by Django 3.2.23 on 2024-02-04 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20240202_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainlinktemplate',
            name='template_name',
            field=models.CharField(default='theme', max_length=150, unique=True, verbose_name='اسم القالب'),
        ),
    ]
