# Generated by Django 3.2.23 on 2024-02-10 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_mainlinktemplate_template_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainlink',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.mainlinktemplate', verbose_name='لون القالب'),
        ),
    ]
