# Generated by Django 3.2.23 on 2023-12-09 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_auto_20231209_0339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='title',
        ),
    ]
