# Generated by Django 3.2.23 on 2023-12-30 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0005_alter_gallery_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='title',
            field=models.CharField(max_length=255, verbose_name='عنوان'),
        ),
    ]
